export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_DETAILS_RESET = "USER_DETAILS_RESET";
export const ORDER_LIST_MY_RESET = "ORDER_LIST_MY_RESET";
export const USER_LIST_RESET = "USER_LIST_RESET";
